config/routes.rb
Rails.application.routes.draw do
	root "rants#index"

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
 
  resources :users do
 		post 'follow', to: 'users#follow', as: 'follow'
 		delete 'unfollow', to: 'users#unfollow', as: 'unfollow'
  end

  resources :rants do
  	resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :follower, class_name: :User
  belongs_to :followed, class_name: :User

  validates :follower_id, uniqueness: { scope: :followed_id }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :rant

  validates :user_id, uniqueness: { scope: :rant_id }
end

app/models/rant.rb
class Rant < ApplicationRecord
  belongs_to :author, class_name: :User
  has_many :likes, dependent: :destroy

  validates :content, presence: true, length: { minimum: 3, maximum: 280 }
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  has_one_attached :cover_image

  has_many :rants, foreign_key: :author_id, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :followings, foreign_key: :follower_id
  has_many :followers, class_name: :Following, foreign_key: :followed_id

  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 50 }
  validates :full_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_path, alert: 'You must be logged in to access this page.' if current_user.nil?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new(rant_id: params[:rant_id])

    if @like.save
      redirect_to rants_path, notice: 'You liked a rant.'
    else
      redirect_to rants_path, alert: 'You cannot like this rant.'
    end
  end

  def destroy
    like = Like.find_by(id: params[:id], user: current_user, rant_id: params[:rant_id])
    if like
      like.destroy
      redirect_to rants_path, alert: 'You disliked a rant.'
    else
      redirect_to rants_path, alert: 'You cannot dislike rant that you did not like before.'
    end
  end
end

app/controllers/rants_controller.rb
class RantsController < ApplicationController
  before_action :set_rant, only: %i[destroy]
  before_action :authorize

  def index
    @following_with_count = Following.group('followings.follower_id').count
    @followers_with_count = Following.group('followings.followed_id').count
    @likes = Like.includes(:rant, :user)
    @likes_with_count = Like.group('likes.rant_id').count
    @users = User.includes(:photo_attachment).order('created_at DESC')
    @rants = Rant.includes(:author).order('created_at DESC')
    @followingz = Following.includes(:follower, :followed)
  end

  def new
    @rant = current_user.rants.new
  end

  def create
    @rant = current_user.rants.new(rant_params)

    if @rant.save
      redirect_to rants_url, notice: 'Rant was successfully created.'
    else
      flash[:alert] = "Content can't be blank"
      redirect_to :rants
    end
  end

  def destroy
    @rant.destroy
    redirect_to rants_url, alert: 'Rant deleted!'
  end

  private

  def set_rant
    @rant = Rant.find(params[:id])
  end

  def rant_params
    params.permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(username: params[:username])

    if user
      session[:user_id] = user.id
      redirect_to rants_path, notice: 'Successfully Logged In'
    else
      flash.now[:alert] = 'Incorrect Username. Try again.'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show]
  before_action :authorize, except: %i[new create]

  def show
    @users = User.includes(:photo_attachment).order('created_at DESC')
    @following_with_count = Following.group('followings.follower_id').count
    @followers_with_count = Following.group('followings.followed_id').count
    @followingz = Following.includes(:follower, :followed)
  end

  def new
    @user = User.new
  end

  def follow
    @following = Following.new(follower_id: current_user.id, followed_id: params[:user_id])
    @following.save
    redirect_to user_path(params[:user_id]), notice: 'Started following'
  end

  def unfollow
    @following = Following.find_by(follower_id: current_user.id, followed_id: params[:user_id])
    @following.destroy
    redirect_to user_path(params[:user_id]), alert: 'Unfollowed User'
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to rants_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :full_name, :photo, :cover_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_avatar(user1)
    result = @users.map { |user| user if user == user1 }.compact
    if result.first.photo.attached?
      image_tag(result.first.photo, width: 64, height: 64, class: 'avatar')
    else
      image_tag('http://www.gravatar.com/avatar/?d=retro', class: 'avatar')
    end
  end

  def default_cover(user1)
    result = @users.map { |user| user if user == user1 }.compact
    if result.first.cover_image.attached?
      image_tag(result.first.cover_image, width: 720, height: 240, class: 'cover-photo')
    else
      image_tag('https://picsum.photos/id/0/720/240', class: 'cover-photo')
    end
  end

  # rubocop:disable Layout/LineLength
  def like_or_dislike_btn(rantt)
    result = @likes.map { |like| like if like.user == current_user && like.rant == rantt }.compact
    if !result.empty?
      link_to('<i class="fa fa-heart" aria-hidden="true"></i>'.html_safe, rant_like_path(id: result.first.id, rant_id: rantt.id), method: :delete, class: 'dislike')
    else
      link_to('<i class="far fa-heart" aria-hidden="true"></i>'.html_safe, rant_likes_path(rant_id: rantt.id), method: :post, class: 'like')
    end
  end

  def delete_or_retweet_btn(rant)
    if current_user.id == rant.author_id
      link_to '<i class="fas fa-trash-alt" aria-hidden="true"></i>'.html_safe, rant, method: :delete, data: { confirm: 'Are you sure you want to delete this rant?' }, class: 'level-item icon'
    else
      link_to '<i class="fa fa-retweet" aria-hidden="true"></i>'.html_safe, '#', class: 'icon'
    end
  end

  def follow_plus(user)
    return if user == current_user

    if followed_users(current_user).include?(user)
      link_to('<div class="icon"><i class="fas fa-times"></i></div>'.html_safe, user_unfollow_path(user.id), method: 'DELETE', class: 'follow-ex')
    else
      link_to('<div class="icon"><i class="fas fa-plus"></i></div>'.html_safe, user_follow_path(user.id), method: 'POST', class: 'follow-plus')
    end
  end

  def list_icon(user)
    '<div class="icon"><i class="fas fa-list-ul"></i></div>'.html_safe if user != current_user
  end

  def follow_plus2(user)
    return unless !followed_users(current_user).include?(user) && current_user != user

    link_to('<div class="icon"><i class="fas fa-plus"></i></div>'.html_safe, user_follow_path(user.id), method: 'POST', class: 'follow-er')
  end

  def followed_users(user)
    @followingz.map { |f| f.followed if f.follower == user }.compact
  end

  def users_following(user)
    @followingz.map { |f| f.follower if f.followed == user }.compact
  end

  def who_to_follow
    @users.map { |user| user if user != current_user && !followed_users(current_user).include?(user) }.compact
  end
  # rubocop:enable Layout/LineLength
end

app/views/layouts/_navigation.html.erb
<nav class="navbar is-info" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a href="/" class="navbar-item logo-name">
      <strong>RANTEN</strong>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-end">
      <% if current_user %>
      <div class="navbar-item">
        <span class="icon">
          <i class="fas fa-pen"></i>
        </span>
      </div>
      <div class="navbar-item">
        <span class="icon">
          <i class="fas fa-envelope"></i>
        </span>
      </div>
      <div class="navbar-item">
        <span class="icon">
          <i class="fas fa-search"></i>
        </span>
      </div>
      <% end %>
      <div class="navbar-item">
        <div class="dropdown is-hoverable is-right">
          <div class="dropdown-trigger">
            <span class="icon">
              <i class="fas fa-cog" aria-controls="dropdown-menu" aria-haspopup="true" aria-hidden="true"></i>
            </span>
          </div>
          <div class="dropdown-menu" id="dropdown-menu" role="menu">
            <div class="dropdown-content">
              <% if current_user %>
              <%= link_to 'Logout', logout_path, class: "dropdown-item", method: :delete %>
              <% else %>
              <%= link_to 'Sign up', new_user_path, class: "dropdown-item" %>
              <%= link_to 'Log in', login_path, class: "dropdown-item" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ranten</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', "https://fonts.googleapis.com/css2?family=Rock+Salt&display=swap", media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag asset_path('favicon.ico') %>
</head>

<body>
  <div class="columns is-gapless">
    <% if current_user %>
    <%= render 'users/profile' %>
    <div class="column">
      <%= render 'layouts/navigation' %>
      <div class="notices">
        <% if notice.present? %>
        <p class="notice" id="notice"> <%= notice %> </p>
        <% end %>

        <% if alert.present? %>
        <p class="alert" id="alert"> <%= alert %> </p>
        <% end %>
      </div>
      <%= yield %>
    </div>
    <% else %>
    <div class="column has-background-white">
      <%= render 'layouts/navigation' %>

      <% if notice.present? %>
      <div class="notice" id="notice">
        <p> <%= notice %> </p>
      </div>
      <% end %>
      <% if alert.present? %>
      <div class="alert" id='alert'>
        <p> <%= alert %> </p>
      </div>
      <% end %>

      <%= yield %>
    </div>
    <% end %>
  </div>

  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</body>
</html>

app/views/rants/_feed.html.erb
<div class="column is-two-thirds ">

	<div class="tabs">
		<ul>
			<li class="is-active"><a>RANTS</a></li>
			<li><a>PHOTOS</a></li>
			<li><a>VIDEOS</a></li>
		</ul>
	</div>
	<section class="feed">
		<article class="box-form">
			<%= render 'rants/form' %>
		</article>

		<article class="boxed">

			<% @rants.each do |rant| %>

			<article class="rant">
				<div class="vatar">
					<%= default_avatar(rant.author) %>
				</div>
				<div class="rant-body">
					<div class="rant-content">
						<strong><%= link_to "#{rant.author.full_name.capitalize}", user_path(rant.author.id), class: "name" %></strong>
						<small class="small"><%= time_ago_in_words(rant.created_at) %></small>
						<p><%= rant.content %></p>
					</div>

					<nav class="level">
						<div class="level-left is-mobile">
							<%= like_or_dislike_btn(rant) %>
							<small class="like-count"><%= @likes_with_count[rant.id] %></small>
							<%= delete_or_retweet_btn(rant) %>
						</div>
					</nav>
					</div>
				</article>

				<% end %>
			</article>
		</section>
	</div>

app/views/rants/_form.html.erb
<%= form_with model: @rant, url: rants_path do |f| %>

		<%= f.label "Rant about it", class: "label" %>
  <div class="field">
  <div class="control">
    <%= f.text_area :content, placeholder: "Rant about something...", id: :content %>
  </div>
</div>

<%= f.submit "Rant", class: "button is-info" %>
<% end %>

app/views/rants/index.html.erb
<div class="container is-fluid bord">
<%= render 'rants/feed' %>
<%= render 'users/who-to-follow' %>

</div>

app/views/users/_form.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">

      <div class="column is-4">

        <h2 class="title is-2">Sign Up</h2>

        <%= simple_form_for(@user) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="field">
         <div class="control">
          <%= f.input :username, 
          autofocus: true,
          input_html: { class: "input", id: :username }, wrapper: false, label_html: {class: "label"} %>
        </div>
      </div>

      <div class="field">
       <div class="control">
        <%= f.input :full_name,
        input_html: { class: "input", id: :full_name }, wrapper: false, label_html: {class: "label"} %>
      </div>
    </div>


    <div class="field">
     <div class="control">
    <strong><%= f.label "Profile photo " %></strong> <br>
      <%= f.file_field :photo,
      input_html: { class: "input" }, wrapper: false, label_html: {class: "label"} %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <strong> <%= f.label "Cover photo " %></strong><br>
      <%= f.file_field :cover_image, input_html: { class: "input" }, wrapper: false, label_html: {class: "label"} %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.button :submit, "Sign up", class: "button is-info is-medium" %>
    </div>
  </div>

  <% end %>

  <br />

</div>
</div>
</div>
</div>

app/views/users/_profile.html.erb
<div class="column is-2 profile">
	<article class="prof">
		<div class="prof-img">
			<%= default_avatar(current_user) %>
		</div>
		
		<div class="prof-name">
			<%= current_user.full_name.upcase %>
		</div>
	</article>

	<div class="follow">
		<div class="folw">
			<p class="numb"><%= @following_with_count[current_user.id] %></p>
			<p class="follow-text">Following</p>
		</div>
		<div class="folw">
			<p class="numb"><%= @followers_with_count[current_user.id] %></p>
			<p class="follow-text">Followers</p>
		</div>
	</div>

	<div>
		<ul class="side-nav">
			<li><a href="/"><i class="fas fa-home" aria-hidden="true"></i> <%= link_to "HOME", root_path%></a></li>
			<li><a href="#"><i class="fas fa-user" aria-hidden="true"></i> <%= link_to "PROFILE", user_path(current_user)%></a></li>
			<li><a href="#"><i class="fas fa-at" aria-hidden="true"></i> CONNECT</a></li>
			<li><a href="#"><i class="fas fa-hashtag" aria-hidden="true"></i> DISCOVER</a></li>
			<li><a href="#"><i class="fas fa-chart-pie" aria-hidden="true"></i> STATISTICS</a></li>
		</ul>
	</div>
</div>

app/views/users/_who-to-follow.html.erb
<div class="column side">

	<p class="head">WHO TO FOLLOW</p>

		<% who_to_follow.each do |user| %>
			<article class="user">
				<div class="">
					<%= default_avatar(user) %>
				</div>
				<div class="">
					<strong><%= link_to "#{user.full_name.capitalize}", user_path(user.id), class: "name" %></strong><br>
					<small>@<%= user.username %></small>
				</div>
			</article>
		<% end %>

</div>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<div class="user-page">
	<div class="user-feed">
		<%= default_cover(@user) %>
		<div class="tabs">
			<ul>
				<li class="is-active"><a>RANTS</a></li>
				<li><a>PHOTOS</a></li>
				<li><a>FOLLOWING</a></li>
				<li><a>FOLLOWERS</a></li>
				<li><a>FAVORITES</a></li>
				<li><a>LISTS</a></li>
			</ul>
		</div>

		<div class="user-rants">
			<% @user.rants.eager_load(:author).each do |rant| %>
			<article class="media">
				<div class="media-left">
					<%= default_avatar(rant.author) %>
				</div>
				<div class="media-content">
					<div class="content">
						<small class="small"><%= time_ago_in_words(rant.created_at) %></small>
						<strong><%= link_to "#{rant.author.full_name.capitalize}", user_path(rant.author.id), class: "name" %></strong><br />
						<small>@<%= rant.author.username %></small><br />
						<p><%= rant.content %></p>
					</div>
				</div>
			</article>
			<% end %>
		</div>

	</div>

	<div class="user-prof">
		<div class="prof-head">
			<%= follow_plus(@user) %>
			<%= default_avatar(@user) %>
			<%= list_icon(@user) %>
		</div>
		<div class="user-name">
			<strong class=""><%= @user.full_name.upcase %></strong><br />
			<strong class="">@<%= @user.username %></strong><br />
		</div>
		

		<div class="user-folw">
			<div>
				<p class="count"><%= @user.rants.count %></p>
				<p class="">Rants</p>
			</div>

			<div>
				<p class="count"><%= @following_with_count[@user.id] %></p>
				<p class="">Following</p>
			</div>
			<div>
				<p class="count"><%= @followers_with_count[@user.id] %></p>
				<p class="">Followers</p>
			</div>
		</div>


		
		<p class="fol-by">FOLLOWED BY</p>
		<div class="user-followers">
			<% users_following(@user).each do |follower| %>

			<article class="users">
				<div>
					<%= default_avatar(follower) %>
				</div>
				
				<div>
					<strong><%= link_to "#{follower.full_name.capitalize}", user_path(follower.id), class: "name" %></strong><br>
					<small>@<%= follower.username %></small>
				</div>
				<%= follow_plus2(follower) %>
			</article>

			<% end %>
		</div>
	</div>
</div>